# Generated by Django 3.2.9 on 2021-11-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='list_22',
            new_name='construction',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='list_33',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='list_11',
            new_name='df',
        ),
    ]
